[project]
org-name = "ballerinax"
version = "0.11.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["ballerina", "aws.s3", "amazon", "client", "connector"]
repository = "https://github.com/ballerina-platform/module-amazons3"
